num_tuple=(2,85,879,15)
sort_num_tuple=tuple(sorted(num_tuple))
s_tuple=("error","soft","application","bug","developer","warning","list","tuple")
programmer_dictionary=tuple(sorted(s_tuple))
print("Числа в правильном порядке",sort_num_tuple,sep=" ;")
print("термены программистов :",programmer_dictionary,sep=",")